function sanitize(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
    .trim();
}

function normalizeEmail(value) {
  return String(value || '').trim().toLowerCase();
}

function isValidEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

function makePlainText(data) {
  const rows = [
    ['Name', data.name],
    ['Email', data.email],
    ['Company', data.company],
    ['Role', data.role],
    ['Program stage', data.program_stage],
    ['Study type', data.study_type],
    ['Therapeutic area', data.therapeutic_area],
    ['Target geography', data.target_geography],
    ['CDA needed?', data.cda_needed],
    ['Short synopsis', data.message],
  ];

  return rows
    .map(([label, value]) => `${label}: ${String(value || '').trim()}`)
    .join('\n');
}

function makeHtml(data) {
  const rows = [
    ['Name', data.name],
    ['Email', data.email],
    ['Company', data.company],
    ['Role', data.role],
    ['Program stage', data.program_stage],
    ['Study type', data.study_type],
    ['Therapeutic area', data.therapeutic_area],
    ['Target geography', data.target_geography],
    ['CDA needed?', data.cda_needed],
    ['Short synopsis', data.message],
  ];

  const tableRows = rows.map(([label, value]) => `
    <tr>
      <td style="padding:10px 12px;border:1px solid #ddd;font-weight:700;background:#f7f6f1;vertical-align:top;width:190px;">${sanitize(label)}</td>
      <td style="padding:10px 12px;border:1px solid #ddd;vertical-align:top;white-space:pre-wrap;">${sanitize(value)}</td>
    </tr>`).join('');

  return `
    <div style="font-family:Arial,sans-serif;color:#111;line-height:1.45;">
      <h2 style="margin:0 0 14px;">New Study-Fit Request from Kindrial Website</h2>
      <table style="border-collapse:collapse;width:100%;max-width:760px;">${tableRows}</table>
      <p style="margin-top:18px;color:#555;font-size:13px;">This message was generated by the Kindrial website Study-Fit form.</p>
    </div>`;
}

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const data = typeof req.body === 'string' ? JSON.parse(req.body || '{}') : (req.body || {});

  if (data._honey) {
    return res.status(200).json({ ok: true });
  }

  const name = String(data.name || '').trim();
  const company = String(data.company || '').trim();
  const email = normalizeEmail(data.email);
  const message = String(data.message || '').trim();

  if (!name || !company || !email || !message) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  if (!isValidEmail(email)) {
    return res.status(400).json({ error: 'Invalid email address' });
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'Missing RESEND_API_KEY environment variable' });
  }

  const to = process.env.LEAD_EMAIL || 'hello@kindrial.com';
  const from = process.env.MAIL_FROM || 'Kindrial Website <hello@kindrial.com>';
  const cc = process.env.LEAD_CC_EMAIL;

  const emailPayload = {
    from,
    to: [to],
    subject: 'New Study-Fit Request from Kindrial Website',
    html: makeHtml({ ...data, email }),
    text: makePlainText({ ...data, email }),
    reply_to: email,
  };

  if (cc) {
    emailPayload.cc = cc.split(',').map(item => item.trim()).filter(Boolean);
  }

  const resendResponse = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(emailPayload),
  });

  if (!resendResponse.ok) {
    const errorText = await resendResponse.text();
    return res.status(502).json({ error: 'Email provider failed', details: errorText });
  }

  return res.status(200).json({ ok: true });
};
